// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", false);
user_pref("app.normandy.startupExperimentPrefs.network.http.spdy.websockets", false);
user_pref("app.normandy.user_id", "788d1d2d-cfc7-4a72-9eb9-17a96d001dbf");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1548895040);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1548895205);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 317440);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1548895010);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"32905\":1548895015859,\"32907\":1548895015859,\"32977\":1548895015859}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"1334\":[1548895016114]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{0902bd76-2f0a-47eb-b298-7e20443d3d00}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1548831600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1548895064937");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1548896880937");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1548895037689");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1548898637689");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1548895208");
user_pref("browser.slowStartup.averageTime", 4897);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190128144255");
user_pref("browser.startup.homepage_override.mstone", "65.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1548895027721");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "56720ff41b394afcb599154c02510034");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0");
user_pref("extensions.lastPlatformVersion", "65.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"545efde1-d8ce-40b2-9a40-4dc8eea97b7d\",\"screenshots@mozilla.org\":\"472bcc6c-0c25-4be8-b922-acffd16532aa\",\"webcompat-reporter@mozilla.org\":\"ae4eb62d-f9e7-450e-bc6b-3914c5d079c1\",\"webcompat@mozilla.org\":\"4e8ab3e1-d73b-41d6-ac69-bbf483ebb567\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1548895212);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190128144255");
user_pref("media.gmp-manager.lastCheck", 1548895210);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 59048);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "119c45f8-c9dc-40e2-8c34-650542a46098");
user_pref("security.sandbox.plugin.tempDirSuffix", "da246ff4-7b5d-4c34-b263-2fb728b3627e");
user_pref("services.blocklist.addons.checked", 1548895268);
user_pref("services.blocklist.gfx.checked", 1548895268);
user_pref("services.blocklist.onecrl.checked", 1548895268);
user_pref("services.blocklist.pinning.checked", 1548895268);
user_pref("services.blocklist.plugins.checked", 1548895268);
user_pref("services.settings.clock_skew_seconds", -58);
user_pref("services.settings.last_etag", "\"1548796224519\"");
user_pref("services.settings.last_update_seconds", 1548895268);
user_pref("services.settings.main.language-dictionaries.last_check", 1548895268);
user_pref("services.settings.main.onboarding.last_check", 1548895268);
user_pref("services.settings.main.sites-classification.last_check", 1548895268);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1548895007);
user_pref("toolkit.telemetry.cachedClientID", "99093a92-772e-477d-a9a8-2415a89c77e1");
user_pref("toolkit.telemetry.previousBuildID", "20190128144255");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
